### ISSUE TITLE
change the keyword from 'nodes' to something else

### ISSUE THREAD

**Issue by Mrkezii** [iannbing/react-simple-tree-menu#102]
Hi, thanks for `react-simple-tree-menu`

I have a very large data set and i'll love to use this library but the only issue is that my child nodes in the tree use the keyword 'children' and not 'nodes', is there a way this can be changed without me having to loop through my data or forking and changing it ?

**Comment by iannbing** [comment]
Unfortunately not. Forking is probably a good idea.
