### ISSUE TITLE
Key is not a prop warning

### ISSUE THREAD

**Issue by jcleefw** [iannbing/react-simple-tree-menu#111]
I've been receiving the following warning every time the tree initially render.

```
Warning: c: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```

I'm semi suspecting it's because of how the data structure is because the attribute `key is being used in the data set. 

Here's how the data array is being created 
```
 elements.map(element => {
      adjusted.push({
        id: element.id,
        key: element.external_identifier,
        label: this.elementLabel(element),
        nodes: this.adjustElementsRecursively(element.children),
      })
    })
```

And here's how it's being used in the render component
```
<TreeMenu data={this.state.data} hasSearch={false} onClickItem={this.props.onClickItem}>
  {({ items }) => (
    <ul className="tree-item-group">
      {items.map(({ key, ...props }) => (
        <ItemComponent
          key={key}
          {...props}
          openedIcon={closeIcon}
          closedIcon={openIcon}
          onClickItem={this.props.onClickItem}
        />
      ))}
    </ul>
  )}
</TreeMenu>
```

Any idea how i can solve the `key` warning?

**Comment by iannbing** [comment]
I tried to reproduce it, but I don't see the warning.
https://codesandbox.io/s/react-simple-tree-menu-demo-7mfiw

Are you using version `1.1.7`?

**Comment by jcleefw** [comment]
Ah hah. No i'm using 1.16. Did an upgrade and it seems the warning is gone now. Thanks
