### ISSUE TITLE
Change/pack the .search css selector

### ISSUE THREAD

**Issue by ognian7** [iannbing/react-simple-tree-menu#113]
The class is very common and can be used outside the component.

**Comment by iannbing** [comment]
Not sure if I understand your question/request. Could you elaborate a bit more?

**Comment by ognian7** [comment]
There is a .search css style which is global and once the component is used
in an application it can affect a component with the same class (the name
search is very common). My suggestion is to rename it or to use more
specific selector.

**Comment by iannbing** [comment]
Ah, you're right. Should've added a prefix for the css classes. Thanks! 
I'm not sure when I'll have time to fix this. Feel free to send your PR 😃.
