### ISSUE TITLE
The whole page breaks if you press the left arrow key in the search bar

### ISSUE THREAD

**Issue by dragidavid2** [iannbing/react-simple-tree-menu#114]
👋

There is an annoying bug where if you click in the search bar on page load and press the left arrow key, the whole thing breaks. Is there a way to work around that or fix that? It even breaks in storybook so its not because of my changes I'm afraid.

Also, can we have an option to turn the whole keyboard event functionality off? 

![ScreenRecording2019-11-21at09233](https://user-images.githubusercontent.com/54030153/69324694-d5a4a980-0c40-11ea-9e04-3186b00e6861.gif)

**Comment by dragidavid2** [comment]
Super quick fix! Thanks! 

When would this be merged into master approximately?

**Comment by iannbing** [comment]
Thanks for reporting this bug. It's been released, version `1.1.8`.
