### ISSUE TITLE
Use with Typescript/React

### ISSUE THREAD

**Issue by tagyoureit** [iannbing/react-simple-tree-menu#121]
I'd like to use this tree in my project with my app, but think I'm running into some compatibility issues.  
![2019-12-05_20-42-24](https://user-images.githubusercontent.com/1646840/70296511-cd4f8100-179f-11ea-8dde-1ac6debdd57b.jpeg)

![2019-12-05_20-39-33](https://user-images.githubusercontent.com/1646840/70296526-d80a1600-179f-11ea-9bf9-61abec99c82e.jpeg)

If I change the first line of index.d.ts to `import * as React from 'react';` I'm able to use the component (but there are still some minor visual issues).  

Am I missing something obvious?  Here are my dependencies:

```
  "dependencies": {
    "@types/concurrently": "^4.1.0",
    "@types/http-server": "^0.10.0",
    "concurrently": "^5.0.0",
    "extend": "^3.0.2",
    "http-server": "^0.12.0",
    "parcel-bundler": "^1.12.3",
    "react-simple-tree-menu": "^1.1.9"
  },
"devDependencies": {
    "@tableau/extensions-api-types": "1.3.1",
    "@tableau/tabextsandbox": "^1.1.0",
    "@tableau/tableau-ui": "^2.1.0",
    "@types/jquery": "^3.3.29",
    "@types/node": "^12.12.14",
    "@types/react": "^16.9.15",
    "@types/react-dom": "^16.9.4",
    "@types/react-router-dom": "^5.1.3",
    "@types/reactstrap": "^8.0.6",
    "babel-polyfill": "^6.26.0",
    "css-loader": "^3.2.1",
    "nodemon": "^2.0.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-router-dom": "^5.0.1",
    "react-switch": "^5.0.0",
    "reactstrap": "^8.2.0",
    "semistandard": "^14.2.0",
    "source-map-loader": "^0.2.4",
    "style-loader": "^1.0.1",
    "ts-loader": "^6.2.1",
    "tslint": "^5.20.1",
    "tslint-config-prettier": "^1.10.0",
    "tslint-react": "^4.1.0",
    "typescript": "^3.7.3"
  },
```

I've also tried to set `"allowSyntheticDefaultImports": false` in tsconfig.json but it didn't seem to make a difference.

TIA.

**Comment by tagyoureit** [comment]
I added the `esModuleInterop: true` flag to tsconfig.json (which also enables `allowSyntheticDefaultImports: true`) and this let me load up the tree without error.

**Comment by iannbing** [comment]
Thanks for reporting this. The type definition of React of this library is out-dated. I'll try updating it and see if it solves the issue.
