### ISSUE TITLE
Width fixed to viewport

### ISSUE THREAD

**Issue by donkeyDau** [iannbing/react-simple-tree-menu#141]
I want to use the tree menu in a sidebar. Items with a width wider than the sidebar result in a y-overflow as the width of the `<ul class="rstm-tree-item-group">` is set to `width: 100vw` and not `width: 100%`. Is there any reason why it's done like this? Is there any possibility to overwrite the style or pass a modified class?

**Comment by iannbing** [comment]
You're right. It should be `100%` instead of `100vw`. PR is welcome 😉
Though you can overwrite it by specifying more specific rules, for example:
```
ul.rstm-tree-item-group {
   width: 100%;
}
```

**Comment by NicolaiSchmid** [comment]
When will the corresponding PR: https://github.com/iannbing/react-simple-tree-menu/pull/142 be published to NPM?

**Comment by iannbing** [comment]
This fix has been released in `v1.1.13` 🙂
