### ISSUE TITLE
Any known issues with next.js ?

### ISSUE THREAD

**Issue by horibu** [iannbing/react-simple-tree-menu#146]
Hi there,

I am trying to get this to work, but somehow I get the same error. I created a new next.js app like it is described in the documentation, added react-simple-menu but, imported it in the specific page.. but I am hitting a wall. I am always getting this:

![Screenshot 2020-01-14 at 08 37 46](https://user-images.githubusercontent.com/5020204/72323932-26b5a480-36aa-11ea-9232-64fb1597974d.png)

Can anyone help me out with this?

Thanks!

**Comment by iannbing** [comment]
Hi, from version ‘1.1.12’, this library only ships esm to support tree-shaking. This means that you need to transpire it in your project. 

Maybe this thread helps.
https://github.com/zeit/next.js/issues/7913

Please provide with me further feedback on this 🙂

**Comment by horibu** [comment]
Hi ,
thanks for the feedback! I tried what u suggested, but didnt manage to get it to work only on a clean next.js install. In my actual project I get the same error after I add the transpile code to next.config.js. I This is my next.config.js file:

![Screenshot 2020-01-15 at 11 28 35](https://user-images.githubusercontent.com/5020204/72426562-3e645a00-378a-11ea-8b3b-756d7e6d4274.png)
![Screenshot 2020-01-15 at 11 28 54](https://user-images.githubusercontent.com/5020204/72426570-41f7e100-378a-11ea-8bc4-915e6af32915.png)

**Comment by iannbing** [comment]
Hi, it seems to be a lot of work to make `nextjs` to work with `esm` modules. I made a new release shipping with `cjs`. Please try version `1.1.14`.
