### ISSUE TITLE
How can I put a custom icon to open/close item? 

### ISSUE THREAD

**Issue by lcuriel** [iannbing/react-simple-tree-menu#152]
I can see in the storybook an example where you use a custom icon when the item is open or close, but in the documentation I can't see how to use a custom icon to open/close  item.

**Comment by iannbing** [comment]
A short example
```
import TreeMenu, { ItemComponent } from 'react-simple-tree-menu';
<TreeMenu data={dataInArray}>
      {({ items }) => (
        <ul className="tree-item-group">
          {items.map(({ key, ...props }) => (
            <ItemComponent
              key={key}
              {...props}
              openedIcon={openedIcon}
              closedIcon={closedIcon}
            />
          ))}
        </ul>
      )}
    </TreeMenu>
```

**Comment by lcuriel** [comment]
Thank you for your answer. 

The last question, How can I put a custom format? I tried use <span> inside tee property label obj.label

![Screen Shot 2020-01-31 at 11 56 02 AM](https://user-images.githubusercontent.com/3791921/73562452-c9974e00-4420-11ea-976d-2b2b196d6938.png)

**Comment by iannbing** [comment]
Could you show your code to reproduce the issue? I don't have the context by viewing the image you posted.

**Comment by iannbing** [comment]
I'll close this issue for now. Feel free to re-open if you have further quesitons.

**Comment by TatianaRG** [comment]
I tried to follow the instruction on this topic but without success. What exactly are the openedIcon={}
 closedIcon={} are expecting? A function?
