### ISSUE TITLE
Menu items deeper than first level cannot be opned with initialOpenNodes

### ISSUE THREAD

**Issue by senal** [iannbing/react-simple-tree-menu#153]
Hi,
I have a use case in which I have to open the menu up to the 3rd level deeper and activate the given node.
E.g
first-parent-node
     first-parent-second-level-node-1
          first-parent-third-level-node-1 <-- active
second-parent-node

So I create the data for the tree as follows
`const data = [
    {
      key: "first-parent",
      label: "first-parent",
      nodes: [
        {
          key: "first-parent-second-level-node-1",
          label: "first-parent-second-level-node-1",
          nodes: [
            {
              key: "first-parent-third-level-node-1",
              label: "first-parent-third-level-node-1",
              nodes: []
            }
          ]
        }
      ]
    },
    {
      key: "second-parent",
      label: "second-parent"
    }
  ];`

And set the data with the initialActiveKey and initialOpenNodes as follows
`const LibraryCategroryIndex : React.FC = () => {

    return (<TreeMenu data={data}  initialActiveKey="first-parent/first-parent-second-level-node-1/first-parent-third-level-node-1"   initialOpenNodes={["first-parent","first-parent-second-level-node-1", "first-parent-third-level-node-1"]}  ></TreeMenu>);
}`
The renders tree looks like the below image.
<img width="843" alt="tree" src="https://user-images.githubusercontent.com/2841066/73600992-38a1ad80-45ad-11ea-90e3-5e7887cb47dc.PNG">

Why I can't expand the tree deeper? Is it a limitation of the tree component or something I do wrong here?

Appreciate your feedback in this regard.

**Comment by iannbing** [comment]
Hi, you need to chain the open node names like initialActiveKey. 

Change [“parent”, “child”, “grandchild”] to [“parent”, “parent/child”, “parent/child/grandchild”]

This is a precaution in the case where the node key is not globally unique.

**Comment by senal** [comment]
@iannbing ,
Thank you very much. It worked!
