### ISSUE TITLE
initialOpenNodes is not updated on re-render of the component

### ISSUE THREAD

**Issue by che7ven** [iannbing/react-simple-tree-menu#154]
I am trying to keep the first node to be open when my component renders but the data is still not available at the point (initialOpenNodes={['']}) as it is fetched via API. Once the data is fetched, TreeMenu renders again with the required data (initialOpenNodes={['<node_name'>']}) but it is not taking the updated prop. I tested this by hardcoding the value and it works fine. So, I assume that the value set on first render is what TreeMenu consumes ignoring the subsequent renders. 

Can you please look into this?

**Comment by iannbing** [comment]
Indeed that’s how it works now. You have a valid use case, thanks. I’ll look into it.

**Comment by iannbing** [comment]
Hi, there is a un-documented prop `resetOpenNodesOnDataUpdate` (it's a boolean, default is `false`). Try set it to `true` and see if it functions as you expected..

**Comment by iannbing** [comment]
I'll close this issue. Feel free to re-open it if the issue presists.

**Comment by ashik-jyothi** [comment]
I am experiencing the same issue even after setting `resetOpenNodesOnDataUpdate` to `true`
