### ISSUE TITLE
Collapse by clicking first level

### ISSUE THREAD

**Issue by mperu92** [iannbing/react-simple-tree-menu#156]
Hello, 
i would know if there's a way to collapse the tree by clicking the whole first level, not only the "+" icon

Thanks!

**Comment by iannbing** [comment]
It's not configurable out-of-box. You need to write your own rendering component. Here's a quick example with the default `ItemComponent`:

```
import TreeMenu, { ItemComponent } from 'react-simple-tree-menu';

<TreeMenu data={treeData}>
    {({ items }) => {
        return <ul> {items.map(item => {
            return <ItemComponent onClick={item.toggleNode}>{item.label}</ItemComponent>
        })}</ul>
    }}
</TreeMenu>
```

The type of `item` in this example is `TreeMenuItem` in the documentation.

**Comment by mperu92** [comment]
#167
