### ISSUE TITLE
Custom component no longer toggling onClick

### ISSUE THREAD

**Issue by Ajaay** [iannbing/react-simple-tree-menu#157]
I've recently updated several packages including react/react-dom and react-simpl-tree-menu. Since doing that, I can no longer get the menu items to toggle on click and I really can't figure out why...

So I was wondering if anyone would be so kind to check over my code and see if there's anything obvious I need to change? I can't figure it out...

https://codesandbox.io/s/magical-fermat-j37x7

Thanks!

**Comment by SpawnAtis** [comment]
Hi. Check it [click](https://codesandbox.io/s/gifted-field-e81jx)

**Comment by SpawnAtis** [comment]
@Ajaay Hi. Check it [click](https://codesandbox.io/s/gifted-field-e81jx)

**Comment by Ajaay** [comment]
Wow thank you @SpawnAtis . I wish I understood how that callAll function is working. I'll try and break it down and see if I can figure it out.

You've saved me a massive headache there though. Thank you for giving your time.
