### ISSUE TITLE
Remove border line.

### ISSUE THREAD

**Issue by Yinxing-Gao** [iannbing/react-simple-tree-menu#159]
Thanks for posting "react-simple-tree-menu".
And can I have a question?
I can see the blue border out of the group tree when I click the children item.
I don't want that. I need to remove that border.
Where I can do that?

**Comment by iannbing** [comment]
You can overwrite the default styling, or simply don't import the default styling and style the whole component from scratch.

**Comment by Yinxing-Gao** [comment]
Ok. Thanks. Just I have overwritten the default styling. And I can control all style. But I can't control the blue border line. How I can that? What is the issues?

**Comment by Yinxing-Gao** [comment]
If I use default style, Where can I control that style?

**Comment by iannbing** [comment]
I think you're referring to the `outline`. Here's the answer you can easily find via google:
https://stackoverflow.com/questions/7648898/how-to-get-rid-of-blue-outer-border-when-clicking-on-a-form-input-field

To overwrite the default styling, import your custom styling after this line.
```
import '../node_modules/react-simple-tree-menu/dist/main.css';
// import './path/to/your/own/styling.css';
```
