### ISSUE TITLE
How I can add other icons before the text?

### ISSUE THREAD

**Issue by Yinxing-Gao** [iannbing/react-simple-tree-menu#160]
Thanks for posting.
How can I change the opened/closed icon (not +/-)?  I want to change the icon. I don't want +/- icon.
And then can I add two Icons at that place? Now I'm making group and user tree. I need to use two icons each groups and users. I need a second icon to identify groups and users. How I can do that?
And can I add react node to <ItemComponent> tag?

**Comment by iannbing** [comment]
In the README, there is a link to the[ storybook demo](https://iannbing.github.io/react-simple-tree-menu/?path=/story/treemenu--default-usage)

and here's the source code for the demo
https://github.com/iannbing/react-simple-tree-menu/blob/master/stories/index.stories.js
This should probably solve most of your issues.
