### ISSUE TITLE
Navigate to props.url in example code

### ISSUE THREAD

**Issue by raynerhoward** [iannbing/react-simple-tree-menu#165]
Probably a dumb question, but using the example code I'm unable to get it to navigate to the url in props.url when I click on a third-level-node:

```
  onClickItem={({ key, label, ...props }) => {
    this.navigate(props.url); // user defined prop
  }}
```

The error is `TypeError: Cannot read property 'navigate' of undefined`

`console.log(props.url)` shows the correct url.

**Comment by iannbing** [comment]
Hi, it's an example how it might look like. You need to implement the function `navigate` yourself. 
The minimal implementation can be
```js
window.location.href = props.url;
```
