### ISSUE TITLE
Show parent nodes on search for children

### ISSUE THREAD

**Issue by christianeide** [iannbing/react-simple-tree-menu#194]
Hi! Thanks for a great package!

If you go to the basic example in the Storybook and search for `Gekko`, then Gekko is shown as expected. But is it possible to also show the parent nodes when you do this search? So that the hierarchy is visible?

Something like this:
![image](https://user-images.githubusercontent.com/15894115/119895351-f6d50d00-bf3d-11eb-9c92-e108b924d399.png)

**Comment by christianeide** [comment]
For future reference: I solved this by adding a property childLabels to all parent elements with a substring of its children, like `childLabels: "Squamata Gekko"`. Then i created a custom search where I also searched through that string for parent elements and returned true if match.

**Comment by iannbing** [comment]
@christianeide  That's a smart workaround! Thanks for sharing.
