### ISSUE TITLE
Is it possible to only close a node when it's active?

### ISSUE THREAD

**Issue by sillyapplemuffin** [iannbing/react-simple-tree-menu#44]
Might be a silly question and sorry for that but here it is :

How can i get a node to close only when it's in active state ? (and keep open workflow intact)
I have not been able to do it myself so i request some help maybe I'm missing something obvious.

Thank you in advance :)

**Comment by iannbing** [comment]
Could you further explain your use case with mockups or live examples? If I have a clearer idea I might find some time to make a working example.

I think it is possible by manipulating ‘activeKey’ ‘openNodes’ and ‘onClickItem’. Whenever a item is clicked, ‘onClickItem’ is fired. You can decide which nodes should be open by updating ‘openNode’ and which node is active by providing ‘activeKey’. Then all the built-in logic will be overwritten.

**Comment by sillyapplemuffin** [comment]
Ok, i got it, i was pretty close ^^"
I was trying to get the active key back as an onClick's argument instead of handling activeKey myself and passing it via the props.
Thank you for your time and your advices !
