### ISSUE TITLE
how to remove searchBox ?

### ISSUE THREAD

**Issue by wslp12** [iannbing/react-simple-tree-menu#45]
i want just remove searchBox 
However, children must be redefined. Is there no other way?

**Comment by sillyapplemuffin** [comment]
I had a quick look for that but it's seems like there is no other way, I can't find any workaround, but I might be wrong.

**Comment by iannbing** [comment]
You’re right. Currently the only way to achieve this is to define your own children. I probably will creat a new prop “hasSearch” to determine if the elements in the “items” has the function prop “search”, and only display the search box if “search” is provided.

It should be a simple request but I’m not available for this until the end of this month. You could either send a PR or wait for 2 more weeks :-)
