### ISSUE TITLE
Does not work with SSR / Gatsby (because UMD)

### ISSUE THREAD

**Issue by MattMcFarland** [iannbing/react-simple-tree-menu#46]
I'm trying to use this with Gatsby, but the problem is the UMD wrapper that is generated in the dist folder is referencing window, which breaks the build because window is not defined in node.  Honestly UMD just adds bloat in any case where someone is using webpack to import your library.  For maximum compatibility, you need multiple export targets though, which is outlined in (this article: https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953)

At any rate, I can't use this library as is, so I'm copy/pasting this into my project instead of using it as a dependency (which really sucks) - if I ever get the time I'll try to work on a PR and fork, but if you can beat me to it, please refactor your build process so that it is compatible with SSR, right now it only works for browser rendering only which means no gatsby and no SSR  

see: 
 - https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953
 - https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

PS: This is an amazing library by the way, the way it was designed is top notch.  While the build export itself isn't compatible, the API and component is the most flexible one I've seen and it deserves a lot more stars!!

**Comment by iannbing** [comment]
You made a very good point! Thanks for the informative advice! I’m currently spending my time with my family. As soon as I’m back to work, I’ll look into this. Really appreciate your feedback :-)

**Comment by iannbing** [comment]
I just merged a PR that fixes this issue. Please help test version `1.0.7-rc.2` and kindly report any further issue.

**Comment by iannbing** [comment]
I'll close this issue for now. Feel free to re-open it if the issue persists.

**Comment by MattMcFarland** [comment]
@iannbing - Version `1.0.7-rc.2` works great! Thanks!
