### ISSUE TITLE
is there a way to bind keyboard shortcuts for the TreeMenu

### ISSUE THREAD

**Issue by nurpax** [iannbing/react-simple-tree-menu#47]
I'd like to be able to browse the menu with arrow up/down, left/right keys.  Up/down would go up & down in the menu items, left/right would close/open the current item if it has children.

Would it work to hook keyboard events and then synthesize click events based on what keys were pressed?

**Comment by iannbing** [comment]
Nice feature request! I have this idea in mind but don’t have time to implement it yet. But it’s totally possible to wrap this component with your own logic. I would just use onKeyDown prop instead of synthesizing onClick though since you can define your own MenuItem component.

I don’t have access to my computer at the moment. I’ll look into in the coming month.

**Comment by nurpax** [comment]
Cool! Yeah so what I had in mind was to capture the onKeyDown event in my MenuItem (which I already render with render props) and then call the onClick callback. What I meant with synthesizing the event was to stick something that looks like enough of an event for your onClick handling code to do the right thing with it. :)

This might be a great thingto have as a built-in feature tho. I use this not for menus but for browsing a pretty large tree with some extra information stored in each node. So far this is working well, but I’m sure the users of my app will be asking for keyboard support.

**Comment by iannbing** [comment]
@nurpax I just merged a PR and made a pre-release `1.1.0-rc.2`. Could you try it out and give feedback? Please note the behavior change: I separate the states 'focused' and 'active', and `ENTER` is equivalent to `onClick`. I'll release `1.1.0` later if you don't have further issues.

**Comment by nurpax** [comment]
Thanks a lot for caring about my feature request. I ended up writing my own treeview component from scratch as I needed some other features too that I couldn’t find from this library. However, I’m happy to offer some feedback now that I read your code. 

1. I modeled the left/right keys such that left works so that:

- first left: if current node is leaf or closed, set parent node as active. if at an open node, close the node. 

Not sure I described the logic completely but if you try how VSCode’s folder tree menu in the left pane works, you’ll get what I mean. IMO this feels really natural and it ”clicked” with my teammates expectations too. 

2. scroll into view. If the item selected by keyboard is out of view (eg. long list and the div has a scrollbar), the selected item should be scrolled into view. I did this with the non-standard scrollIntoViewIfNeeded (standard is scrollIntoView but this doesn’t feel very good, at least in my code). So I had to plug refs into my rendered tree items and call the corresponding DOM method via the item refs. 

3. not related to your PR but was one motivation for rolling my own component. Not sure if this is possible in your code. I needed the open status for the subtree starting from the selected item. So I added a tree pruning step that computes the currently opened nodes and sends this back via ”on item selected” callback. I needed this because I needed a copy&pasteable plain text version of the selected tree.

**Comment by iannbing** [comment]
Thanks for the feedback! I like your suggestion and it's actually a very easy change (so I did it 😄). Regarding the 3rd point, every MenuItem knows almost everything about the tree, such as `openNodes` and even `searchTerm`. By some simple filter function, you can get the open nodes of the sub-tree.

The scroll to view is indeed tricky. Thanks for sharing!
