### ISSUE TITLE
on open?

### ISSUE THREAD

**Issue by mhutfield** [iannbing/react-simple-tree-menu#67]
Hi, really like this component, however I'm not sure how to fire an event when an item is opened to reveal its children, all I can see is the onClick event. Any way to asynchronously load more children when an item is opened?

Thanks

**Comment by iannbing** [comment]
Every item has a prop `toggleNode`, which is a function that opens its children. You can check in the story for its usage https://github.com/iannbing/react-simple-tree-menu/blob/c65ff7c1e00d978ba19fcbcd2c737fb12d215133/stories/index.stories.js#L40

Hope this helps.

**Comment by mhutfield** [comment]
Hi thanks for your super fast response. Yeah I know to load asynchronously it needs to be done separately and put back into the data prop, that's not a problem. I just mentioned it to clarify what I was trying to do. So if you click an item it fires the onclick handler, but if you click the plus icon in that item it drops down and reveals children. What I was asking is how to hook onto that dropdown event, so i can run code to asynchronously fetch children for the next level down. Basically I need a way of distinguishing between clicking an item to select it and dropping it down to reveal the children. Is there a way? Thanks so much for your help

**Comment by iannbing** [comment]
Instead of feeding `toggleNode` directly, wrap it with your own function
```
<ToggleIcon on={isOpen} onClick={() => {
    toggleNode();
    yourOwnFunction();
   }} 
   />
```

**Comment by mhutfield** [comment]
Ok thanks for your help :)

**Comment by JasonLunsford** [comment]
I have this exact same question. I appreciate how straight forward your answer is, but I'm not sure how to apply it. Where would I insert this code?:

<ToggleIcon on={isOpen} onClick={() => {
    toggleNode();
    yourOwnFunction();
   }} 
   />
