### ISSUE TITLE
Feature Request: Separate type definitions

### ISSUE THREAD

**Issue by Sureiya** [iannbing/react-simple-tree-menu#73]
Hey,

First off, thanks for all your hard work on this package. I'm using it to create a select input for hierarchical data, and I'd like to be able to extend your interfaces.

With that in mind, could we consider moving the types and interfaces to *.d.ts files, to facilitate easy module exports without dirtying namespaces?

**Comment by iannbing** [comment]
Could you test if version `1.1.3-rc.1` allows you to import the definitions? I exposed all the inter-referred types and interfaces, so it should cover everything you need.

**Comment by iannbing** [comment]
Tested from my side. Releasing `1.1.3`.
