### ISSUE TITLE
initialOpenNodes is not working as expected

### ISSUE THREAD

**Issue by agentS** [iannbing/react-simple-tree-menu#75]
Hey,

I stumbled upon issue #36 and tried to use your solution for my issue. Unfortuantely, `initialOpenNodes` is not working for me when using version 1.1.2. I am able to control the open nodes using the property `openNodes` instead of `initialOpenNodes`, but the user is not able to interact with the tree in this case. I want the user to be able to interact with the tree and to control the open/collapsed items from my code.

Below you can find the code for my tree menu component.

```jsx
class GraphPropertyView extends React.Component {
  handleClick = (key, label, ...properties) => {};

  render() {
    const { classes } = this.props;

    const properties = this.processProperties(this.props.properties, {
      index: 0,
    });
    const openNodeKeys = this.determineOpenNodes(properties, {
      currentLevel: 0,
    });
    console.log(openNodeKeys);
    return (
      <div className={classes.graphPropertyContainer}>
        <TreeMenu
          data={properties}
          initialOpenNodes={openNodeKeys}
          onClickItem={this.handleClick}
          hasSearch={false}
        />
      </div>
    );
  }

  // emulate call by reference by using a context object
  processProperties(properties, context) {
    let treeData = [];
    for (let property of properties) {
      let addedProperty = {
        key: context.index.toString(),
        label: property.name,
        nodes: []
      };
      ++context.index;
      if (typeof property === "object" && property.children) {
        addedProperty.nodes = this.processProperties(
          property.children,
          context
        );
      }
      treeData.push(addedProperty);
    }
    return treeData;
  }

  // emulate call by reference by using a context object
  determineOpenNodes(properties, context) {
    let openNodeKeys = [];
    for (let property of properties) {
      if (this.props.currentLevel > context.currentLevel) {
        openNodeKeys.push(property.key);
      }
      if ((property.nodes) && (property.nodes.length > 0)) {
        ++context.currentLevel;
        openNodeKeys.push(...this.determineOpenNodes(property.nodes, context));
        --context.currentLevel;
      }
    }
    return openNodeKeys;
  }
}
```

Btw, thank you so much for your great work!

**Comment by iannbing** [comment]
Hello,

Please refer to the storybook demo and this [story](https://github.com/iannbing/react-simple-tree-menu/blob/86585f7fab6d8ca55658b495c870db7bf84846a7/stories/index.stories.js#L143). The issue you encountered is not caused by the component itself.

Your render function execute 2 recursions, and each render takes lots of resources for even rendering a small set of data. Usually you shouldn't put compute-intensive jobs inside of your render function.

I'd suggest extract your data processing part out, and only feed clean data into your React components.

**Comment by agentS** [comment]
I found the issue. `initialOpenNodes` is only executed when the component is mounted. However, I need expand and collapse certain levels from my code. Is there any way to set the open nodes while still allowing the user to interact with the tree menu?

I also moved the recursion out of the render method. Thank you for the hint!

**Comment by iannbing** [comment]
It would be easier if you could share your code via codesandbox.

**Comment by agentS** [comment]
I created a [demo codesandbox application](https://codesandbox.io/s/react-tree-menu-demo-hgl8x). Expanding the tree programatically using the button does not work. However, when I set `initiallyOpenProperties` on creating the state in the constructor, the tree is expanded.

**Comment by iannbing** [comment]
Exactly. The first render will pick up initial state from your Component, which should set in the constructor, which is then assigned to initialOpenNodes.

The handleExpandTree function is not needed, unless you want it take full control over the TreeMenu. Setting the initial value is usually handled in the constructor or componentDidMount (sometimes comoonentDidUpdate), depending on your use case.

**Comment by agentS** [comment]
Okay, let me explain the bigger picture. Your tree menu view is part of a bigger view. I basically have a graph which has nodes and each of these nodes has a tree hierarchy of properties. When I click a node, I want to display the tree of properties. Therefore, the tree view is updated with new data quite frequently. I also want the user to be able to expand and collapse the entire tree or certain levels programatically. In order to achieve the latter functionality I need a way to change the expanded items in the tree menu while still allowing the user to manually expand and collapse items. The button in my example should expand the entire tree when clicked. Is there any way to do accomplish this with your library? Thank you so much for your answer!

**Comment by iannbing** [comment]
Now it's clearer to me. So you want a way to "reset" the openNodes. Currently the library doesn't have an easy way to achieve this. But it's a valid use case. Thanks! Please track this issue #78 instead.
