### ISSUE TITLE
"Warning: u: `key` is not a prop" in console.

### ISSUE THREAD

**Issue by JasonLunsford** [iannbing/react-simple-tree-menu#86]
Great tree view component, very powerful and easy to use. Thank you for releasing it!

I just implemented it and followed the data structure as per the documentation. In my console react is throwing an error:

Warning: u: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

Is this something that I can fix or will it require a update to the component code?

Thank you!

**Comment by JasonLunsford** [comment]
Follow up, the error is occuring on line 195 in main.js. Here is the block of code at fault:

`return n.default.createElement("div", {
        role: "img",
        "aria-label": "Toggle",
        className: "toggle-icon-symbol"
      }, t ? "-" : "+");
    },
        u = function u(e) {
      var t = e.hasNodes,
          r = void 0 !== t && t,
          c = e.isOpen,
          u = void 0 !== c && c,
          f = e.level,
          s = void 0 === f ? 0 : f,
          l = e.onClick,
          p = e.toggleNode,
          d = e.active,
          y = e.focused,
          v = e.key,
          b = e.label,
          h = void 0 === b ? "unknown" : b,
          m = e.style,
          j = void 0 === m ? {} : m;`

**Comment by iannbing** [comment]
Glad to hear that you like this component!

This warning is to prevent users using `key` wrongly, especially if you spread the `props`.
To resolve this warning is to explicitly assign your `key` to the component's `key`.
```
<TreeViewMenu data={treeData}>
    {({ search, items }) => (
        <ul>
            {items.map(({key, ...props}) => (
              <li key={key} {...props} />
            ))}
        </ul>
    )}
</TreeViewMenu>
```

Hope this helps.

**Comment by JasonLunsford** [comment]
Thank you for replying!

Here is my code as it stands now, in combination with the code you suggested:

                    <TreeMenu
                        hasSearch={false}
                        data={tree}
                        onClickItem={node => {
                            this.handleTreeClick(node);
                        }}
                    >
                        {({ search, items }) => (
                            <ul>
                                {items.map(({key, ...props}) => (
                                    <li key={key} {...props} />
                                ))}
                            </ul>
                        )}
                    </TreeMenu>

The trouble is, now React is throwing several errors, including:

> Warning: React does not recognize the `openNodes` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `opennodes` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

> Warning: React does not recognize the `hasNodes` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasnodes` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

and

> Warning: Received `false` for a non-boolean attribute `focused`.
> 
> If you want to write it to the DOM, pass a string instead: focused="false" or focused={value.toString()}.
> 
> If you used to conditionally omit it with focused={condition && value}, pass focused={condition ? value : undefined} instead.

Thank you for your help.

**Comment by iannbing** [comment]
Ah, sorry my bad.

My example code above isn’t correct.
In order to prevent all the warnings of such kind. You need a custom component to explicitly consumes the props instead of using native elements like li. 

You can check how I implement it [here](https://github.com/iannbing/react-simple-tree-menu/blob/master/src/TreeMenu/renderProps.tsx).

**Comment by Alannek** [comment]
Hi, First of all thank you for the awesome component. But i am still having issues with this warning. This is my snippet -> 

`    <TreeViewMenu data={unflatten(treeData)} hasSearch={false}>
    {({ search, items }) => (
        <ul style={{listStyle:"none"}}>
            {items.map(props => (
              <ItemComponent {...props} key={props.id} />
            ))}
        </ul>
    )}
      </TreeViewMenu>`

And from your explanation I am not sure, how to actually solve it. Thanks a lot in advance and best regards !

**Comment by iannbing** [comment]
@Alannek 

The warning is referring to this line
```
{items.map(props => (<ItemComponent {...props} key={props.id} />))}
```

It is warning you that the object spread`{...props}` include 'key', which shouldn't be treated as a normal prop, although you overwrite it with `key={props.id}` (also note that `id` is not part of the default props, I assume that you add it yourself).

What you need to change is following:
```js
// instead of this
{...props}  // key is part of the props
// do this
{key, ...props}  // key is not part of props
```
This means that you no longer have `key` in `{...props}`, so that `ItemComponent` does not get `key` from `{...props}` and it will only have `key={props.id}`.
```
{items.map(({key, ...props}) => (<ItemComponent {...props} key={props.id} />))}
```

Hope it's clear to you.

**Comment by AvishekNath** [comment]
Still getting error --> Warning: u: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)


Code-->


  const treeData = [
    {
      key: "first-level-node-1",
      id: "first-level-node-1",
      label: "Node 1 at the first level",
      nodes: [
        {
          key: "second-level-node-1",
          id: "second-level-node-1",
          label: "Node 1 at the second level",
          nodes: [
            {
              key: "third-level-node-1",
              id: "third-level-node-1",
              label: "Last node of the branch",
              nodes: [] // you can remove the nodes property or leave it as an empty array
            }
          ]
        }
      ]
    },
    {
      key: "first-level-node-2",
      id: "first-level-node-2",
      label: "Node 2 at the first level"
    }
  ];


 <TreeMenu
          hasSearch={true}
          data={treeData}
          onClickItem={node => {
            //this.handleTreeClick(node);
          }}
        >
          {({ search, items }) => (
            <ul className="tree-item-group">
              {items.map(({ key, ...props }) => (
                <ItemComponent {...props} key={props.id} />
              ))}
            </ul>
          )}
        </TreeMenu>


Please help!!
