### ISSUE TITLE
onClickItem modification

### ISSUE THREAD

**Issue by rakzeee** [iannbing/react-simple-tree-menu#87]
Thank you for your work! Strong and simple component.
Sorry for (probably) stupid question (I am relatively new to React), but is it possible to implement onClickItem method in such way that it will call toggleNode if node has children nodes?
Thank you in advance.

**Comment by iannbing** [comment]
`onClickItem` is a generic function that will be called inside of `onClick` of a tree item.
See below for example, when you fire `onClick` function of any item, `clicked` will be logged.

To call `onClick` and `toggleNode` together, you only need to create another function that execute both of them. 

```
<TreeViewMenu data={treeData} onClickItem={() => console.log('clicked')}>
    {({ search, items }) => (
        <ul>
            {items.map(({onClick, toggleNode, key, ... props}) => (
              <li key={key} onClick={() => {
                       onClick();  // console.log('clicked');
                       if(toggleNode) toggleNode();
                   }} {...props}/>
            ))}
        </ul>
    )}
</TreeViewMenu>
```

I typed the above code directly without a IDE. There might be some syntax error, but you get the idea :-)

**Comment by rakzeee** [comment]
Thank you!
So, in this case, I should build my menu manually (you use <ul> and <li> here in your example)?

**Comment by iannbing** [comment]
Technically yes.
But you can re-used the default UI. Check README. Find the sentence `If you want to extend the minial UI components, they are exported at your disposal.`. Combined with the above example you'll figure out.
