### ISSUE TITLE
Can we add custom icons/images to the tree for each node?

### ISSUE THREAD

**Issue by Vassant** [iannbing/react-simple-tree-menu#89]
Hi, thanks for such an easy to use tree view component. It helped me a lot as I'm using it to display dynamic data fetched from the back-end.
I wanted to know if we can add custom icons/images to each tree node instead of the default "+/-".
If possible, could you please guide me on how to implement the same as I'm new to React.

**Comment by iannbing** [comment]
I'd make 'ToggleIcon' replace-able, then you can extend it from `ItemComponent`. It will be a nice "good first issue". PR welcome!

**Comment by Vassant** [comment]
As I'm new to React (just one month into it ), I did not quite get what you are saying. Could you please elaborate a little? 😅

**Comment by iannbing** [comment]
Glad to hear that you're learning React. It's a nice practice for beginners 😃. I'll give you some guidance, and it would be awesome if you could contribute to this project.

What you were asking for was part of [this file](https://github.com/iannbing/react-simple-tree-menu/blob/master/src/TreeMenu/renderProps.tsx)

Specifically in this component.
```
export const ItemComponent: React.FunctionComponent<TreeMenuItem> = ({
  hasNodes = false,
  isOpen = false,
  level = 0,
  onClick,
  toggleNode,
  active,
  focused,
  key,
  label = 'unknown',
  style = {},
}) => (
  <li
    className={classNames(
      'tree-item',
      { 'tree-item--active': active },
      { 'tree-item--focused': focused }
    )}
    style={{
      paddingLeft: `${DEFAULT_PADDING +
        ICON_SIZE * (hasNodes ? 0 : 1) +
        level * LEVEL_SPACE}rem`,
      ...style,
    }}
    role="button"
    aria-pressed={active}
    key={key}
    onClick={onClick}
  >
    {hasNodes && (
      <div
        className="toggle-icon"
        onClick={e => {
          hasNodes && toggleNode && toggleNode();
          e.stopPropagation();
        }}
      >
        <ToggleIcon on={isOpen} />
      </div>
    )}
    {label}
  </li>
);
```
You'll see `ToggleIcon` is inside, which you want to replace with your own Icon, via the props. The goal is to allow the following usage (note that `MyAwesomeIcon` is your own Icon).

```
import TreeMenu, { defaultChildren, ItemComponent } from 'react-simple-tree-menu';

<TreeViewMenu data={treeData}>
    {({ search, items }) => (
        <ul>
            {items.map(props => (
              <ItemComponent {...props, icon: MyAwesomeIcon} />
            ))}
        </ul>
    )}
</TreeViewMenu>
```

**Comment by Alannek** [comment]
Is this still opened or may I contribute on this? Would you recommend me the Best way how to contribute on this project? How to actually change your sources? Best refards, Aleš.

**Comment by iannbing** [comment]
@Alannek Yes, it's still open. Feel free to contribute.
If you're new to open source projects, I highly recommend [this free online course](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github).

I don't have specific rules for contributors. Send your PR, and I can help you along the way.

**Comment by oriuken** [comment]
Hey @iannbing , I've sent you a PR about this issue. 

It's my first time contributing to an opensource project at github so I apologize if I skip part of the process..

**Comment by TatianaRG** [comment]
Is this usable now? Thanks
