### ISSUE TITLE
Set item active after toggling

### ISSUE THREAD

**Issue by Alannek** [iannbing/react-simple-tree-menu#90]
Hi again, once more thank you for this component and Fast replying. I would like to ask... Is it possible to set item as active after toggle event is executed? This works fine when the on click event is fired, but i would like to also set item as active after toggle is executed, not just on click. Thanks for an answer. Best regards, Aleš.

**Comment by iannbing** [comment]
Check the API document for `ItemComponent` [here](https://github.com/iannbing/react-simple-tree-menu#treemenuitem). When `onClick` is fired, the item will become active (i.e. `active` will become `true`).

So basically what you want to achieve is to fire `toggleNode` and `onClick` at the same time when user click on the item (or the toggle Icon).

This behavior is quite different from the default behavoir, so you need to implement your own `ItemCompnent`, which behaves as described above.
