### ISSUE TITLE
How to programmatically toggle a tree node?

### ISSUE THREAD

**Issue by JasonLunsford** [iannbing/react-simple-tree-menu#91]
Question pretty much says it all. I need to toggle (close) the whole tree (or even better, a single node) following an event occuring outside the immediate tree scope. I've tried setting isOpen to false but that doesn't work. Ideally I could fire a "reset" prop method of some kind that automatically closes all open tree nodes.

Any help will be gratefully appreciated!

**Comment by JasonLunsford** [comment]
Just to clarify, I can leverage the existing reset method that exists as part of the Children props, but this only works within the scope of the tree:

`            <TreeMenu
                hasSearch={false}
                data={data}
                initialOpenNodes={[data[0].id]}
            >
                { ({ items, reset }) => (
                    <React.Fragment>
                        <button onClick={reset}>Reset</button>
                        <ul>
                            {
                                items.map(props => (
                                    <ListItem
                                        onToggleItem={onToggleItem}
                                        onClickItem={onClickItem}
                                        {...props}
                                    />
                                ))
                            }
                        </ul>
                    </React.Fragment>
                )}
            </TreeMenu>`

**Comment by JasonLunsford** [comment]
Figured this out. The answer is to surface the reset method up and out of the tree component, into a global space (I used Redux's Store, your mileage may vary). Then you can fire the reset prop wherever you like.

**Comment by iannbing** [comment]
Thanks for sharing your solution. That's exactly what this library is designed for. By exposing the API inside of the component, you can freely control the behavior of the Tree Menu 😃

**Comment by sanderaiaots** [comment]
Any code example how to solve this?
I'm bit stuck where I need programmatically  open some tree branches in TreeMenu, but all I have managed so far is to change from "+" to "-" in front of tree, but chider won't open.
