### ISSUE TITLE
Placeholder Searchbox

### ISSUE THREAD

**Issue by mumapu** [iannbing/react-simple-tree-menu#92]
Hello! How to change only the placeholder of searchbox?

**Comment by hm-mx** [comment]
Hi, we don't plan to support customizations on the default UI. With that said, the default UI is also exported at your disposal (see README). You can customize them as you wish for your purpose.

**Comment by iannbing** [comment]
Hi, we don't plan to support customizations on the default UI. With that said, the default UI is also exported at your disposal (see README). You can customize them easily.
