### ISSUE TITLE
[Feature] Initial Values should be effective in every render

### ISSUE THREAD

**Issue by pmh1031** [iannbing/react-simple-tree-menu#94]
The following values have no effect on the initially rendered tree menu...

initialOpenNodes
initialActiveKey
initialFocusKey

Also, the demo at https://codesandbox.io/s/react-tree-menu-demo-dbx8d 
is not working with the same issue.

**Comment by iannbing** [comment]
All of the initial values kick in when the component is instantiated (so that's why they're called 'initial'). In your codesandbox example, you need to replace `initialOpenNodes` with `openNodes`.

**Comment by pmh1031** [comment]
If the value for data is changed, for example nodes are added, then the tree is re-rendered with the new node data but the initial values are no longer reflected in what is rendered.  Even though the tree is re-rendered with changed node data the initial values you mentioned above are not maintained.  In other words, if I want the first node to be highlighted each time the tree is updated with new nodes how would I do that?  Note that in this circumstance I would still like the user to be able to select other nodes which they are unable to do if activeKey is used to highlight a node when the tree is rendered.

**Comment by iannbing** [comment]
If I understand you correctly, you're assuming that 'initialOpenNodes' should be effective in every render? Very interesting. This was not how I designed the API, but you seem to provide a valid use case.

> It's not a bug; it's a feature. 😄 

Your proposal starts to make sense to me. I'll reopen the issue .

**Comment by pmh1031** [comment]
Thanks for the quick responses :)
