### ISSUE TITLE
How to highlight a selected tree node?

### ISSUE THREAD

**Issue by JasonLunsford** [iannbing/react-simple-tree-menu#99]
Simple question - the "active" property in the node's props seems to always be false, even following the click event. How do I programmatically determine if a node has been clicked on, so that I can apply an "active" class to the node.

Here is the code I have as it is today. Any suggestions / help you can offer will be very appreciated.

`const ListItem = (props) => {
    return (
        <li
            style={{
                paddingLeft: DEFAULT_PADDING + ICON_SIZE + props.level * LEVEL_SPACE,
                cursor:      'pointer'
            }}
        >
            {props.hasNodes &&
            <React.Fragment>
                <ToggleIcon
                    on={props.isOpen}
                    onClick={() => { toggleAction(props); }}
                />
                <FlavorIcon type={props.type} />
            </React.Fragment>
            }
            {!props.hasNodes &&
            <FlavorIcon
                type={props.type}
                style={{
                    marginLeft: '1.3rem'
                }}
            />}
            <span
                role="none"
                onClick={() => {
                    props.onClickItem(props);
                }}
            >
                {props.label}
            </span>
        </li>
    );
};

const TreeMenuWrapper = ({ data, onToggleItem, onClickItem, saveTreeReset }) => {
    if (data.length > 0) {
        return (
            <TreeMenu
                hasSearch={false}
                data={data}
                initialOpenNodes={[data[0].id]}
            >
                { ({ items, reset }) => (
                    <React.Fragment>
                        {saveTreeReset(reset)}
                        <ul>
                            {
                                items.map(props => (
                                    <ListItem
                                        onToggleItem={onToggleItem}
                                        onClickItem={onClickItem}
                                        {...props}
                                    />
                                ))
                            }
                        </ul>
                    </React.Fragment>
                )}
            </TreeMenu>
        );
    } else {
        return null;
    }
};`

**Comment by JasonLunsford** [comment]
I'll leave the question posted here because I would love to get the "official" answer, but for what it's worth I got this working with a simple use of useState hook:

`const ListItem = (props) => {
    return (
        <li
            role="none"
            style={{ paddingLeft: DEFAULT_PADDING + ICON_SIZE + props.level * LEVEL_SPACE, cursor: 'pointer' }}
            onClick={() => props.setActiveNode(props)}
            className={props.id === props.activeNode.id ? classes.active : ''}
        >
            {props.hasNodes &&
            <React.Fragment>
                <ToggleIcon
                    on={props.isOpen}
                    onClick={() => { toggleAction(props); }}
                />
                <FlavorIcon type={props.type} />
            </React.Fragment>
            }
            {!props.hasNodes &&
            <FlavorIcon
                type={props.type}
                style={{
                    marginLeft: '1.3rem'
                }}
            />}
            <span role="none" onClick={() => { props.onClickItem(props); }}>{props.label}</span>
        </li>
    );
};

const TreeMenuWrapper = ({ data, onToggleItem, onClickItem, saveTreeReset }) => {
    const [activeNode, setActiveNode] = useState({});

    if (data.length > 0) {
        return (
            <TreeMenu
                hasSearch={false}
                data={data}
                initialOpenNodes={[data[0].id]}
            >
                { ({ items, reset }) => (
                    <React.Fragment>
                        {saveTreeReset(reset)}
                        <ul>
                            {
                                items.map(props => (
                                    <ListItem
                                        onToggleItem={onToggleItem}
                                        onClickItem={onClickItem}
                                        setActiveNode={setActiveNode}
                                        activeNode={activeNode}
                                        {...props}
                                    />
                                ))
                            }
                        </ul>
                    </React.Fragment>
                )}
            </TreeMenu>
        );
    } else {
        return null;
    }
};`

**Comment by iannbing** [comment]
You can see the `TreeMenu` [demo](https://iannbing.github.io/react-simple-tree-menu/?path=/story/treemenu--default-usage), try to use your browser dev tool to inspect it. You can see that `tree-item--active` is assigned when the item's active value is `true`.

You can also read how I achieve it in this [file](https://github.com/iannbing/react-simple-tree-menu/blob/6117b2ed54644212c943a09feab9610e6780e830/src/TreeMenu/renderProps.tsx#L53)

The problem in your code is this line
```
className={props.id === props.activeNode.id ? classes.active : ''}
```
I guess you want to do something like this:
```
className={props.active ? 'item-highlight' : 'item'}
```

It's hard to give further advice without a codesandbox/jsfiddle example.
